// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQXAJgV5jBx_bGVeFQMYj9IWJRAcBLZVI',
    appId: '1:429372303044:web:bdd68bb053c580125f0b91',
    messagingSenderId: '429372303044',
    projectId: 'tackle4loss-888b5',
    authDomain: 'tackle4loss-888b5.firebaseapp.com',
    storageBucket: 'tackle4loss-888b5.firebasestorage.app',
    measurementId: 'G-VT26J7TC05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6p6UoMQakbwcQlwNKpsTdRiq3g_AN6qI',
    appId: '1:429372303044:android:7a684fb75ffa1ab65f0b91',
    messagingSenderId: '429372303044',
    projectId: 'tackle4loss-888b5',
    storageBucket: 'tackle4loss-888b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQcZTi_1oyTbJIie8ArMkIOAJYb1uLLNM',
    appId: '1:429372303044:ios:033bb8436053bbcc5f0b91',
    messagingSenderId: '429372303044',
    projectId: 'tackle4loss-888b5',
    storageBucket: 'tackle4loss-888b5.firebasestorage.app',
    iosBundleId: 'com.bigsliktobi.tackle4Loss',
  );
}
